name: ish_top
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    # qaren fokus korsataman hozir qarab turin
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository


  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  pack:
    path: packages/pack
  formz: ^0.4.0
  google_fonts: ^3.0.1
  meta: ^1.7.0
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  email_validator: '^2.1.16'
  flutter_svg: ^1.1.1+1
  lottie: ^1.4.3
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^2.0.1
  easy_localization: ^3.0.1
  connectivity_plus: ^2.3.7
  url_launcher: ^6.1.4
  json_serializable: ^6.3.1
  flutter_linkify: ^5.0.2
  intl: ^0.17.0
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.8
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2

  dio: ^4.0.6
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1

  dotted_border: ^2.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2
  build_runner: ^2.2.0


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 900
